// Ícones de Sistema
export { default as Icon3Pontos } from './Icones de Sistema/Icon3Pontos.vue'
export { default as IconAcessibilidade } from './Icones de Sistema/IconAcessibilidade.vue'
export { default as IconAcessos } from './Icones de Sistema/IconAcessos.vue'
export { default as IconAdicionar } from './Icones de Sistema/IconAdicionar.vue'
export { default as IconAjuda } from './Icones de Sistema/IconAjuda.vue'
export { default as IconAplicativo } from './Icones de Sistema/IconAplicativo.vue'
export { default as IconAvancar } from './Icones de Sistema/IconAvancar.vue'
export { default as IconAvatar } from './Icones de Sistema/IconAvatar.vue'
export { default as IconAviso } from './Icones de Sistema/IconAviso.vue'
export { default as IconCadastro } from './Icones de Sistema/IconCadastro.vue'
export { default as IconCalendario } from './Icones de Sistema/IconCalendario.vue'
export { default as IconCarrinho } from './Icones de Sistema/IconCarrinho.vue'
export { default as IconChat } from './Icones de Sistema/IconChat.vue'
export { default as IconCheck } from './Icones de Sistema/IconCheck.vue'
export { default as IconChevronDown } from './Icones de Sistema/IconChevronDown.vue'
export { default as IconChevronUp } from './Icones de Sistema/IconChevronUp.vue'
export { default as IconClips } from './Icones de Sistema/IconClips.vue'
export { default as IconCompartilhar } from './Icones de Sistema/IconCompartilhar.vue'
export { default as IconConfiguracoes } from './Icones de Sistema/IconConfiguracoes.vue'
export { default as IconCopiar } from './Icones de Sistema/IconCopiar.vue'
export { default as IconDeslike } from './Icones de Sistema/IconDeslike.vue'
export { default as IconDocumento } from './Icones de Sistema/IconDocumento.vue'
export { default as IconDocumentoEscrito } from './Icones de Sistema/IconDocumentoEscrito.vue'
export { default as IconDownload } from './Icones de Sistema/IconDownload.vue'
export { default as IconEditar } from './Icones de Sistema/IconEditar.vue'
export { default as IconEmail } from './Icones de Sistema/IconEmail.vue'
export { default as IconEnquadramento } from './Icones de Sistema/IconEnquadramento.vue'
export { default as IconEnviar } from './Icones de Sistema/IconEnviar.vue'
export { default as IconExcluir } from './Icones de Sistema/IconExcluir.vue'
export { default as IconFavoritar } from './Icones de Sistema/IconFavoritar.vue'
export { default as IconFechar } from './Icones de Sistema/IconFechar.vue'
export { default as IconFiltrar } from './Icones de Sistema/IconFiltrar.vue'
export { default as IconFoto } from './Icones de Sistema/IconFoto.vue'
export { default as IconGride } from './Icones de Sistema/IconGride.vue'
export { default as IconHome } from './Icones de Sistema/IconHome.vue'
export { default as IconImprimir } from './Icones de Sistema/IconImprimir.vue'
export { default as IconInformacao } from './Icones de Sistema/IconInformacao.vue'
export { default as IconLike } from './Icones de Sistema/IconLike.vue'
export { default as IconLink } from './Icones de Sistema/IconLink.vue'
export { default as IconLista } from './Icones de Sistema/IconLista.vue'
export { default as IconLogin } from './Icones de Sistema/IconLogin.vue'
export { default as IconLogout } from './Icones de Sistema/IconLogout.vue'
export { default as IconManual } from './Icones de Sistema/IconManual.vue'
export { default as IconMenu } from './Icones de Sistema/IconMenu.vue'
export { default as IconMensagem } from './Icones de Sistema/IconMensagem.vue'
export { default as IconNotificacao } from './Icones de Sistema/IconNotificacao.vue'
export { default as IconNotificacaoAlerta } from './Icones de Sistema/IconNotificacaoAlerta.vue'
export { default as IconPesquisar } from './Icones de Sistema/IconPesquisar.vue'
export { default as IconProibido } from './Icones de Sistema/IconProibido.vue'
export { default as IconQrcode } from './Icones de Sistema/IconQrcode.vue'
export { default as IconRelogio } from './Icones de Sistema/IconRelogio.vue'
export { default as IconRestart } from './Icones de Sistema/IconRestart.vue'
export { default as IconSeguranca } from './Icones de Sistema/IconSeguranca.vue'
export { default as IconSenha } from './Icones de Sistema/IconSenha.vue'
export { default as IconSenhaOff } from './Icones de Sistema/IconSenhaOff.vue'
export { default as IconSenhaOn } from './Icones de Sistema/IconSenhaOn.vue'
export { default as IconSetaParaBaixo } from './Icones de Sistema/IconSetaParaBaixo.vue'
export { default as IconSetaParaCima } from './Icones de Sistema/IconSetaParaCima.vue'
export { default as IconSite } from './Icones de Sistema/IconSite.vue'
export { default as IconSol } from './Icones de Sistema/IconSol.vue'
export { default as IconTelefone } from './Icones de Sistema/IconTelefone.vue'
export { default as IconUpload } from './Icones de Sistema/IconUpload.vue'
export { default as IconVoltar } from './Icones de Sistema/IconVoltar.vue'

// Ícones de Feedback
// export { default as IconSucesso } from './IconSucesso.vue'
// export { default as IconErro } from './IconErro.vue'
// export { default as IconAtencao } from './IconAtencao.vue'
// export { default as IconNeutro } from './IconNeutro.vue'

// Ícones de Modalidades
// export { default as IconCarros } from './IconCarros.vue'
// export { default as IconMotos } from './IconMotos.vue'
// export { default as IconImoveis } from './IconImoveis.vue'
// export { default as IconPesados } from './IconPesados.vue'
// export { default as IconServicos } from './IconServicos.vue'

// Ícones de Negócio
// export { default as IconAssembleia } from './IconAssembleia.vue'
// export { default as IconBoleto } from './IconBoleto.vue'
// export { default as IconCartao } from './IconCartao.vue'
// export { default as IconConsorcio } from './IconConsorcio.vue'
// export { default as IconContemplacao } from './IconContemplacao.vue'
// export { default as IconCota } from './IconCota.vue'
// export { default as IconLance } from './IconLance.vue'
// export { default as IconPagamento } from './IconPagamento.vue'

// Ícones de Serviços
export { default as IconAssembleiaServico } from './Icones de Serviços/IconAssembleia.vue'
export { default as IconBoletoServico } from './Icones de Serviços/IconBoleto.vue'
export { default as IconCanalDeAtendimento } from './Icones de Serviços/IconCanalDeAtendimento.vue'
export { default as IconCarreiras } from './Icones de Serviços/IconCarreiras.vue'
export { default as IconCartaoServico } from './Icones de Serviços/IconCartao.vue'
export { default as IconComissao } from './Icones de Serviços/IconComissao.vue'
export { default as IconConsorcioServico } from './Icones de Serviços/IconConsorcio.vue'
export { default as IconContemplacaoServico } from './Icones de Serviços/IconContemplacao.vue'
export { default as IconCotaServico } from './Icones de Serviços/IconCota.vue'
export { default as IconDetalhesDaCota } from './Icones de Serviços/IconDetalhesDaCota.vue'
export { default as IconDevolucao } from './Icones de Serviços/IconDevolucao.vue'
export { default as IconFiliais } from './Icones de Serviços/IconFiliais.vue'
export { default as IconGovernanca } from './Icones de Serviços/IconGovernanca.vue'
export { default as IconGrupo } from './Icones de Serviços/IconGrupo.vue'
export { default as IconPagamentoServico } from './Icones de Serviços/IconPagamento.vue'
export { default as IconParceiros } from './Icones de Serviços/IconParceiros.vue'
export { default as IconQuemSomos } from './Icones de Serviços/IconQuemSomos.vue'
export { default as IconResultadoAssembleia } from './Icones de Serviços/IconResultadoAssembleia.vue'
export { default as IconSimulacao } from './Icones de Serviços/IconSimulacao.vue'

// Ícones de Modalidades
export { default as IconCarros } from './Icones de Modalidades/IconCarros.vue'
export { default as IconImoveis } from './Icones de Modalidades/IconImoveis.vue'
export { default as IconMotos } from './Icones de Modalidades/IconMotos.vue'
export { default as IconPesados } from './Icones de Modalidades/IconPesados.vue'
export { default as IconServicosModalidade } from './Icones de Modalidades/IconServicos.vue'
